version: "3"

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    container_name: mariadb
    volumes:
   #   - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=root
